# Generated by Django 2.0.10 on 2019-01-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='title',
            new_name='name',
        ),
    ]
