# Generated by Django 2.0.10 on 2019-01-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20190128_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='start_questions_answers',
            new_name='first_qa',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='is_valid_qa_tree',
            field=models.BooleanField(default=False),
        ),
    ]
