# Generated by Django 2.0.10 on 2019-01-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_questionnairesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairesession',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
